apiVersion: v1
kind: Secret
metadata:
  name: webapp-secret
type: Opaque
data:
  SECRET_KEY: TGFUT0FUYiRnMWZuMDdeY3RrJCRecUJsJDZaXjFXQiFhTGNoTUJHV3Y1c3R3NCZoOU55eWolJlFUeVpEJUtvMXBFOXlnNUZlNWZ3ZXFzdDk=